### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by norygami** [norygami/ANARCHY#1]
### Features
- [ ] Interaction system
- [ ] Individual Healthpools for Characters
- [ ] Ultimates
_See MeleeT implementation
Implement ResourceStack as Cost_
- [ ] Music Player

### Weapons
- [ ] Colt1911 Chamber/Reload Block + Priority
- [ ] Model12 WeaponMontage FollowerAnimInstance
- [ ] Overall Rifle animations

### Characters
- [ ] Adjust PhysAsset

### Boss
- [ ] HP-Bar
- [ ] Buff BossLauncher
- [ ] Beam as GameplayAbility
- [ ] Decrease NotifyWindow on AnimMontage
- [ ] Crushing/Slamming/Grabbing/Throwing
_Wait for Sale on Giant Anim Pack_

### NPC
- [ ] Check Player/Bit collision detection
	
### SRS
- [ ] Fix Outline
	_Diversify Depth Masks
	Implement own ScreenSpace Outline
	Check feasability Material Outline_
- [ ] Check Shader feasability on VRoid Models

### Audio
- [ ] BossTrigger InputEvent
- [ ] OnCue Trigger as OutputEvent
- [ ] WeaponSfx
